# ./serverless.yml

service: youtube-embed-parser

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-esbuild
  - serverless-offline


functions:
  myFunction:
    handler: index.handler
    events:
      - http:
          path: /
          method: post