service: youtube-embed-parser  # 서비스 이름

build:
  esbuild:
    # Enable or Disable bundling the function code and dependencies. (Default: true)
    bundle: false
    # Enable minifying function code. (Default: false)
    minify: false


provider:
  name: aws  # AWS 사용
  runtime: nodejs20.x  # Node.js 20 버전 사용
  region: ap-northeast-2  # 기본 리전 설정 (원하는 리전으로 수정 가능)
  stage: dev  # 배포 단계 (development 단계)

  iam:
    role:
      statements:  # Lambda가 필요한 IAM 권한 추가
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*

functions:
  parseYoutubeEmbed:  # Lambda 함수 이름
    handler: .build/index.handler  # 함수 핸들러 정의 (handler.js 파일 내에 parseYoutubeEmbed 함수 사용)
    events:
      - http:
          path: youtube/parse  # API Gateway로 Lambda 함수를 트리거하는 HTTP 경로
          method: post  # HTTP 메서드 (GET)

package:
  include:
    - .build/**
  exclude:
    - node_modules/**
